function skillsMember() {
    return {
        title: 'Skills',
        skills: [
            { name: 'JavaScript', value: 90 },
            { name: 'React', value: 85 },
            { name: 'Node.js', value: 80 },
            { name: 'MongoDB', value: 70 },
            { name: 'Express', value: 75 },
            { name: 'HTML', value: 85 },
            { name: 'CSS', value: 80 },
            { name: 'Bootstrap', value: 80 },
            { name: 'SASS', value: 70 },
            { name: 'jQuery', value: 80 },
            { name: 'PHP', value: 70 },
            { name: 'MySQL', value: 70 },
            { name: 'Python', value: 60 },
            { name: 'Django', value: 60 },
            { name: 'C/C++', value: 50 },
            { name: 'Java', value: 50 },
            { name: 'Git', value: 80 },
            { name: 'Photoshop', value: 70 },
            { name: 'Illustrator', value: 60 },
            { name: 'Figma', value: 80 },
            { name: 'Sketch', value: 70 },
            { name: 'InVision', value: 70 },
            { name: 'Zeplin', value: 70 },
            { name: 'Adobe XD', value: 70 },
            { name: 'Microsoft Office', value: 90 },
            { name: 'Google Suite', value: 90 },
            { name: 'Trello', value: 90 },
            { name: 'Slack', value: 90 },
            { name: 'Asana', value: 90 },
            { name: 'JIRA', value: 80 },
            { name: 'Confluence', value: 80 },
            { name: 'Basecamp', value: 80 },
            { name: 'Redmine', value: 70 },
            { name: 'Bitbucket', value: 80 },
            { name: 'GitHub', value: 80 },
            { name: 'GitLab', value: 80 },
            { name: 'Docker', value: 70 },
            { name: 'Kubernetes', value: 70 },
            { name: 'Kubernetes', value: 70 },
        ]
    }
}
